[package]
name = "rusty-downloader"
version = "0.1.0"
authors = ["Andrei Tanana <andrei.tanana@deltatre.it>"]
edition = "2018"

[dependencies]
reqwest = "0.9.6"
select = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rayon = "1.0"